from pathlib import Path

base = Path(r'C:\Users\joshu\osha-safety-violations')

(base / 'requirements.txt').write_text("apify==3.7.0\ncrawlee[cheerio]==0.6.5\n", encoding='utf-8')

(base / 'Dockerfile').write_text(
    "FROM apify/actor-python:3.14\n"
    "COPY --chown=myuser:myuser requirements.txt ./\n"
    "RUN pip install -r requirements.txt && pip freeze\n"
    "COPY --chown=myuser:myuser . ./\n"
    "RUN python -m compileall -q osha_safety_violations/\n"
    'CMD ["python", "-m", "osha_safety_violations"]\n',
    encoding='utf-8'
)

(base / 'README.md').write_text(
    '# osha-safety-violations\n'
    '\n'
    'Apify actor that scrapes OSHA enforcement data from public establishment search and inspection pages. '
    'Returns structured contact and penalty records.\n'
    '\n'
    '## Buyer personas\n'
    '\n'
    '**B2B** — compliance teams, safety consultants, insurance underwriters, EHS platforms, legal-tech companies.\n'
    '\n'
    '**B2C** — freelance safety auditors, journalists, civic-tech projects, newsletter authors wanting enforcement summaries.\n'
    '\n'
    '## Example input\n'
    '\n'
    '```json\n'
    '{\n'
    '  "startUrls": [{"url": "https://www.osha.gov/enforcement/establishment-search-results?state=TX"}],\n'
    '  "maxRequestsPerCrawl": 200,\n'
    '  "establishmentLinkSelector": "a[href*=\'/establishment/\']",\n'
    '  "inspectionLinkSelector": "a[href*=\'/inspection/\']",\n'
    '}\n'
    '```\n'
    '\n'
    '## Output fields\n'
    '\n'
    'Each result includes EIN, company name, site address, city, state, zip, inspection ID, date, inspection type, severity, violations found, and total penalties.\n',
    encoding='utf-8'
)

(base / '.actor' / 'actor.json').write_text(
    '{\n'
    '  "name": "osha-safety-violations",\n'
    '  "title": "OSHA Safety Violations Scraper",\n'
    '  "description": "Scrapes OSHA enforcement inspection data and emits structured contact + penalty records.",\n'
    '  "version": "0.1",\n'
    '  "meta": {"templateId": "python-cheerio"},\n'
    '  "input": "INPUT_SCHEMA.json",\n'
    '  "output": "OUTPUT_SCHEMA.json",\n'
    '  "pricing": {\n'
    '    "payPerEvent": {\n'
    '      "events": [\n'
    '        {"name": "violation_record", "pricePerUnit": 5},\n'
    '        {"name": "safety_snapshot", "pricePerUnit": 10}\n'
    '      ],\n'
    '      "pricingInfo": "$0.05 per violation record, $0.10 per inspection snapshot."\n'
    '    }\n'
    '  }\n'
    '}\n',
    encoding='utf-8'
)

(base / '.actor' / 'input_schema.json').write_text(
    '{\n'
    '  "title": "OSHA Safety Violations Input",\n'
    '  "type": "object",\n'
    '  "properties": {\n'
    '    "startUrls": {\n'
    '      "title": "Start URLs",\n'
    '      "type": "array",\n'
    '      "editor": "requestListSources",\n'
    '      "default": [{"url": "https://www.osha.gov/enforcement/establishment-search-results?state=TX"}],\n'
    '      "prefill": [{"url": "https://www.osha.gov/enforcement/establishment-search-results?state=TX"}],\n'
    '      "description": "OSHA establishment search result pages to crawl."\n'
    '    },\n'
    '    "maxRequestsPerCrawl": {\n'
    '      "title": "Max requests per crawl",\n'
    '      "type": "integer",\n'
    '      "editor": "number",\n'
    '      "default": 200,\n'
    '      "description": "Optional cap on total HTTP requests for the run."\n'
    '    },\n'
    '    "establishmentLinkSelector": {\n'
    '      "title": "Establishment link CSS selector",\n'
    '      "type": "string",\n'
    '      "editor": "textfield",\n'
    '      "default": "a[href*=\'/establishment/\']",\n'
    '      "description": "CSS selector to extract establishment detail links from listing pages."\n'
    '    },\n'
    '    "inspectionLinkSelector": {\n'
    '      "title": "Inspection link CSS selector",\n'
    '      "type": "string",\n'
    '      "editor": "textfield",\n'
    '      "default": "a[href*=\'/inspection/\']",\n'
    '      "description": "CSS selector to extract inspection detail links from establishment pages."\n'
    '    },\n'
    '    "userAgent": {\n'
    '      "title": "User agent",\n'
    '      "type": "string",\n'
    '      "editor": "textfield",\n'
    '      "default": "Apify-osha-safety-violations/1.0 (+https://github.com/joshuapinkerton-stack/osha-safety-violations)",\n'
    '      "description": "User-Agent sent with each request."\n'
    '    }\n'
    '  }\n'
    '}\n',
    encoding='utf-8'
)

(base / '.actor' / 'output_schema.json').write_text(
    '{\n'
    '  "type": "object",\n'
    '  "properties": {\n'
    '    "results": {\n'
    '      "title": "Results",\n'
    '      "type": "array",\n'
    '      "items": {\n'
    '        "type": "object",\n'
    '        "properties": {\n'
    '          "ein": {"title": "EIN", "type": "string"},\n'
    '          "companyName": {"title": "Company name", "type": "string"},\n'
    '          "siteAddress": {"title": "Site address", "type": "string"},\n'
    '          "city": {"title": "City", "type": "string"},\n'
    '          "state": {"title": "State", "type": "string"},\n'
    '          "zip": {"title": "Zip", "type": "string"},\n'
    '          "inspectionId": {"title": "Inspection ID", "type": "string"},\n'
    '          "date": {"title": "Date", "type": "string"},\n'
    '          "inspectionType": {"title": "Inspection type", "type": "string"},\n'
    '          "severity": {"title": "Severity", "type": "string"},\n'
    '          "violationsFound": {"title": "Violations found", "type": "integer"},\n'
    '          "totalPenalties": {"title": "Total penalties", "type": "number"}\n'
    '        }\n'
    '      }\n'
    '    }\n'
    '  }\n'
    '}\n',
    encoding='utf-8'
)

(base / 'osha_safety_violations' / '__init__.py').write_text('', encoding='utf-8')

(base / 'osha_safety_violations' / 'main.py').write_text(
    'from __future__ import annotations\n\n'
    'from apify import Actor\n'
    'from crawlee.crawlers import CheerioCrawler\n'
    'from osha_safety_violations.routes import router\n\n\n'
    'async def main() -> None:\n'
    '    async with Actor:\n'
    '        actor_input = await Actor.get_input() or {}\n'
    '\n'
    '        max_requests = int(actor_input.get("maxRequestsPerCrawl", 200))\n'
    '        user_agent = actor_input.get(\n'
    '            "userAgent",\n'
    '            "Apify-osha-safety-violations/1.0 (+https://github.com/joshuapinkerton-stack/osha-safety-violations)",\n'
    '        )\n'
    '\n'
    '        crawler = CheerioCrawler(\n'
    '            max_requests_per_crawl=max_requests,\n'
    '            max_request_retries=4,\n'
    '            request_handler=router,\n'
    '            additional_http_error_status_codes=[403, 429],\n'
    '        )\n'
    '\n'
    '        start_urls = actor_input.get("startUrls") or []\n'
    '        if start_urls:\n'
    '            initial_requests = [\n'
    '                {\n'
    '                    "url": item.get("url"),\n'
    '                    "user_data": {"url_type": "listing"},\n'
    '                }\n'
    '                for item in start_urls\n'
    '                if item.get("url")\n'
    '            ]\n'
    '        else:\n'
    '            Actor.log.info("No startUrls provided; running with empty crawl.")\n'
    '            initial_requests = []\n'
    '\n'
    '        await crawler.run(initial_requests)\n',
    encoding='utf-8'
)

(base / 'osha_safety_violations' / 'routes.py').write_text(
    'from __future__ import annotations\n\n'
    'from apify import Actor\n'
    'from crawlee.crawlers import Router\n'
    'from crawlee._types import BasicCrawlingContext\n\n\n'
    'router = Router[BasicCrawlingContext]()\n\n\n'
    '@router.default()\n'
    'async def listing_handler(context: BasicCrawlingContext) -> None:\n'
    '    Actor.log.info(f"Listing: {context.request.url}")\n'
    '\n'
    '    try: \n'
    '        await Actor.charge("safety_snapshot", {"url": context.request.url})\n'
    '    except RuntimeError as exc:\n'
    '        Actor.log.warning(f"Charge skipped (non-billing run): {exc}")\n'
    '\n'
    '    link_selector = context.request.user_data.get(\n'
    '        "establishment_link_selector",\n'
    '        "a[href*=\'/establishment/\']",\n'
    '    )\n'
    '    async for _ in context.request.enqueue_links(\n'
    '        selector=link_selector,\n'
    '        label="establishment",\n'
    '        user_data={"url_type": "establishment"},\n'
    '    ):\n'
    '        pass\n'
    '\n'
    '    async for _ in context.request.enqueue_links(\n'
    '        selector="a[rel=\'next\'], .pagination-next, .next a",\n'
    '        label="listing",\n'
    '        user_data={"url_type": "listing"},\n'
    '    ):\n'
    '        pass\n'
    '\n'
    '\n'
    '@router.handler("establishment")\n'
    'async def establishment_handler(context: BasicCrawlingContext) -> None:\n'
    '    Actor.log.info(f"Establishment page: {context.request.url}")\n'
    '\n'
    '    async for _ in context.request.enqueue_links(\n'
    '        selector="a[href*=\'/inspection/\']",\n'
    '        label="inspection",\n'
    '        user_data={"url_type": "inspection"},\n'
    '    ):\n'
    '        pass\n'
    '\n'
    '\n'
    '@router.handler("inspection")\n'
    'async def inspection_handler(context: BasicCrawlingContext) -> None:\n'
    '    Actor.log.info(f"Inspection page: {context.request.url}")\n'
    '    dom = context.request.loaded_dom\n'
    '\n'
    '    def _text(sel: str) -> str | None:\n'
    '        if dom is None:\n'
    '            return None\n'
    '        try:\n'
    '            el = dom.select_one(sel)\n'
    '            return el.get_text(strip=True) if el else None\n'
    '        except Exception:\n'
    '            return None\n'
    '\n'
    '    company_name = _text("h1")\n'
    '    ein = _text("dd:contains(\'EIN\')")\n'
    '    address = _text("dd:contains(\'Address\'):last-of-type")\n'
    '    date = _text(".date, .inspection-date")\n'
    '    inspection_type = _text(".inspection-type, td:contains(\'Type\'):first-of-type + td")\n'
    '    severity = _text(".severity, .hazard-category")\n'
    '\n'
    '    violations_count = 0\n'
    '    if dom is not None:\n'
    '        try:\n'
    '            violations_count = len(dom.select(".violation-row, .citation-row"))\n'
    '        except Exception:\n'
    '            violations_count = 0\n'
    '\n'
    '    record = {\n'
    '        "ein": ein,\n'
    '        "companyName": company_name,\n'
    '        "siteAddress": address,\n'
    '        "city": None,\n'
    '        "state": None,\n'
    '        "zip": None,\n'
    '        "inspectionId": context.request.url.rstrip("/").split("/")[-1],\n'
    '        "date": date,\n'
    '        "inspectionType": inspection_type,\n'
    '        "severity": severity,\n'
    '        "violationsFound": violations_count,\n'
    '        "totalPenalties": 0.0,\n'
    '    }\n'
    '\n'
    '    payload = {"url": context.request.url, "record": record}\n'
    '    await Actor.push_data(payload)\n'
    '\n'
    '    try:\n'
    '        await Actor.charge("violation_record", payload)\n'
    '    except RuntimeError as exc:\n'
    '        Actor.log.warning(f"Charge skipped (non-billing run): {exc}")\n',
    encoding='utf-8'
)

print('All actor files written to', base)
